### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MalleChristo** [PixiEditor/PixiEditor#490] opened 2023-03-19 12:24 UTC
** IMPORTANT: Drop the "crash-2023-03-19_13-22-10_098.zip" file in here **
[crash-2023-03-19_13-22-10_098.zip](https://github.com/PixiEditor/PixiEditor/files/11010957/crash-2023-03-19_13-22-10_098.zip)
Crashes on start, no (quick) solution. Likely short-term solution, remove pallets/swatches, as i was importing a few of them, but this would limit the amount i could have, which would be annoying, somewhat.

**Comment by flabbet** [comment] 2023-03-19 13:18
So after removing palettes and and swatches program doesn't crash?

**Comment by MalleChristo** [comment] 2023-03-19 13:53
Haven't tried. Had to go and do something else. Just tried the program out
for a second, imported the colours and I broke it within the first five
minutes of use.

After a reboot of my pc, the program seems to work again without having had
a need to remove anything.

Imported a few more, there doesn't seem to be an issue.

Still a strange behaviour, wouldn't know what the issue could be, i'm not a
programmer.
I Noticed the program doesn't enjoy the auto hide feature of the MS taskbar.

**Comment by flabbet** [comment] 2023-03-19 14:22
According to the crash report, the issue is associated with updates checking, if the issue persists, you can disable auto-update checking in the settings 
![image](https://user-images.githubusercontent.com/25402427/226182393-5d4aee60-ed2d-49bb-8c5f-82d825f0b812.png)

**Comment by CPKreu** [comment] 2024-09-20 11:57
This was probably fixed by e7f0ed0777d40f69d3e43b72ca0794af8a6d017d #482

**Closed by CPKreu** 2024-09-20 11:57 UTC
